### PR TITLE
Feature/language support scan check

### PR DESCRIPTION
**Pull request by TomShlaim**
@ntedgi It's a dummy PR - I'll delete it soon

### CODE REVIEW

**Comment by ntedgi** [comment]
> @ntedgi It's a dummy PR - I'll delete it soon

💪
Can you open in separate issues
- Update angular cli
- Fix link issue with playground unit teshe to reflect changes from ‘lib’ dir

**Comment by TomShlaim** [comment]
@ntedgi Do you mean by this to open separate branches?
I'm afraid that my commits aren't well separated.

And just to emphasize, this specific PR is just for testing the nodejs scan problem.

**Comment by ntedgi** [comment]
> @ntedgi Do you mean by this to open separate branches?
> 
> I'm afraid that my commits aren't well separated.
> 
> 
> 
> And just to emphasize, this specific PR is just for testing the nodejs scan problem.

I mean here 

https://github.com/ntedgi/node-efficientnet/issues

For each small-medium change (for example: ‘upgrade angular cli’ )
open an new issue assign it with the correct labels .
and then each change should be in separate branch

**Comment by TomShlaim** [comment]
@ntedgi 
Np, just one thing - It seems that I don't have permissions to add labels

**Comment by ntedgi** [comment]
On it

**Comment by ntedgi** [comment]
> On it

Now you basically do anything include push to origin master 🚧☠️

**Pull request closed without merging**
