### PR TITLE
Create he.json

### PR DESCRIPTION
**Pull request by Zoniso**
fork repo and update

### CODE REVIEW

**Comment by dikiogres** [comment]
hello im interested in this problem, i would like to work on it

**Comment by ntedgi** [comment]
@dikiogres the issue listed here #37

**Comment by Androthorn** [comment]
Hey there, I just got into Computer Science Uni. I've been studying alone and just heard about Hacktober. Navigating through it I've found your project and would love to contribute in any way possible!

**Comment by ntedgi** [comment]
@Androthorn pick any one of the issues here https://github.com/ntedgi/node-efficientnet/issues
Let me know if you need help

**Pull request closed without merging**
