### PR TITLE
Feature/language support

### PR DESCRIPTION
**Pull request by TomShlaim**

### CODE REVIEW

**Comment by TomShlaim** [comment]
This is a fix for :
https://github.com/ntedgi/node-efficientnet/issues/56

**Comment by TomShlaim** [comment]
@ntedgi 
Finally solved all the problems - I'll split it to separate branches later as discussed and let you know once I'm done.

**Comment by TomShlaim** [comment]
Should be merged after : 
https://github.com/ntedgi/node-efficientnet/pull/89
https://github.com/ntedgi/node-efficientnet/pull/90

**Comment by TomShlaim** [comment]
@ntedgi I've merged main into the branch - I think it's ready to be merged after your approval.

**Review by ntedgi — APPROVED** [review]
👑

**Pull request merged**
