### PR TITLE
Feature/replace `jimp` with `sharp`, support more image format and better performance

### PR DESCRIPTION
**Pull request by luoye-fe**

### CODE REVIEW

**Comment by luoye-fe** [comment]
💢 💢 💢 `libvips` install is so xx.

**Comment by ntedgi** [comment]
any updates? can i help with that?

**Comment by luoye-fe** [comment]
There are two problems,

1、`libvips` install, macOS is ok, but linux cannot be called after installation
2、`heic` format detect is not very accurate, I’m not sure if it’s the image format or image process

**Comment by ntedgi** [comment]
> There are two problems,
> 
> 1、`libvips` install, macOS is ok, but linux cannot be called after installation
> 2、`heic` format detect is not very accurate, I’m not sure if it’s the image format or image process

ok about heic lets make another future request only to figure out what is the problem there .
il take a look on the libvips issue at linux builds

**Pull request closed without merging**
